#pragma once
#include "Object/Object.h"
#include "Object/ObjectFactory.h"
#include "Component/SceneComponent.h"
#include "Core/TickFunction.h"
#include "Collision/OverlapInfo.h"
#include "Camera/MinimalViewInfo.h"

class FArchive;

#include <type_traits>
enum ELevelTick;
struct FActorTickFunction;
class UWorld;
class ULevel;
class UPrimitiveComponent;
class UBillboardComponent;

class AActor : public UObject
{
    friend struct FActorTickFunction;
public:
	DECLARE_CLASS(AActor, UObject)
	AActor();
	~AActor() override;

	virtual void BeginPlay();
	virtual void Tick(float DeltaTime);
	virtual void EndPlay();

	bool HasActorBegunPlay() const { return bActorHasBegunPlay; }

	void Serialize(FArchive& Ar) override;
	UObject* Duplicate(UObject* NewOuter = nullptr) const override;

	// 컴포넌트 생성 + Owner 설정 + 등록 + 렌더 상태 생성
	template<typename T>
	T* AddComponent() {
		static_assert(std::is_base_of_v<UActorComponent, T>,
			"AddComponent<T>: T must derive from UActorComponent");
		T* Comp = UObjectManager::Get().CreateObject<T>(this);
		Comp->SetOwner(this);
		OwnedComponents.push_back(Comp);
		bPrimitiveCacheDirty = true;
		Comp->CreateRenderState();
		MarkPickingDirty();
		SyncEditorBillboardVisibility();
		return Comp;
	}

	// UClass 기반 런타임 컴포넌트 생성
	UActorComponent* AddComponentByClass(UClass* Class);

	void RemoveComponent(UActorComponent* Component);

	// 외부에서 생성된 컴포넌트를 등록 (역직렬화 등)
	void RegisterComponent(UActorComponent* Comp);

	void SetRootComponent(USceneComponent* Comp);
	USceneComponent* GetRootComponent() const { return RootComponent; }
	void EnsureEditorBillboardForActor();
	void SyncEditorBillboardVisibility();

	const TArray<UActorComponent*>& GetComponents() const { return OwnedComponents; }
	template<typename T>
	T* GetComponentByClass() const
	{
		static_assert(std::is_base_of_v<UActorComponent, T>,
			"GetComponentByClass<T>: T must derive from UActorComponent");
		for (UActorComponent* Component : OwnedComponents)
		{
			if (T* TypedComponent = Cast<T>(Component))
				return TypedComponent;
		}
		return nullptr;
	}
	// Transform — Location
	FVector GetActorLocation() const;
	void SetActorLocation(const FVector& Location);
	void AddActorWorldOffset(const FVector& Delta);

	// Transform — Rotation
	FRotator GetActorRotation() const;
	void SetActorRotation(const FRotator& NewRotation);
	void SetActorRotation(const FVector& EulerRotation);

	// Transform — Scale
	FVector GetActorScale() const;
	void SetActorScale(const FVector& NewScale);

	// Direction
	FVector GetActorForward() const;

	void CalcCamera(float DeltaTime, FMinimalViewInfo& OutResult);


	UWorld* GetWorld() const;
	ULevel* GetLevel() const;


	bool IsVisible() const { return bVisible; }
	void SetVisible(bool Visible);
	bool IsActorMovementLocked() const { return bLockActorMovement; }
	void SetActorMovementLocked(bool bLocked) { bLockActorMovement = bLocked; }
	const FString& GetFolderPath() const { return FolderPath; }
	void SetFolderPath(const FString& InFolderPath) { FolderPath = InFolderPath; }
	const FString& GetTag() const { return Tag; }
	void SetTag(const FString& InTag) { Tag = InTag; }
	bool HasTag(const FString& InTag) const { return !InTag.empty() && Tag == InTag; }

	// Tick 필요 여부 — false면 Tick 호출 자체를 건너뜀 (StaticMesh 등)
	bool bNeedsTick = true;
	bool bTickInEditor = false;

	const TArray<UPrimitiveComponent*>& GetPrimitiveComponents() const;
	bool IsQueuedForPartitionUpdate() const { return bQueuedForPartitionUpdate; }
	void SetQueuedForPartitionUpdate(bool bQueued) { bQueuedForPartitionUpdate = bQueued; }
	
	FActorTickFunction PrimaryActorTick;

	bool IsActorSelected() const { return bIsSelected; }
	void SetActorSelected(bool InFlag) { bIsSelected = InFlag; }

	// Overlap
	//void MarkOverlappingDirty() { bIsOverlappingDirty; }
	//bool IsOverlappingDirty() const { return bIsOverlappingDirty; }
	bool IsOverlappingActor(const AActor* Other) const;

	virtual void NotifyActorBeginOverlap(AActor* OtherActor) {}
	virtual void NotifyActorEndOverlap(AActor* OtherActor) {}
	virtual void NotifyActorHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, const FHitResult& Hit) {}
protected:
	virtual void TickActor( float DeltaSeconds, ELevelTick TickType, FActorTickFunction& ThisTickFunction );
	
	void MarkPickingDirty();
	UBillboardComponent* FindEditorOnlyBillboardComponent() const;
	bool HasNonEditorOnlyPrimitiveComponent() const;

	USceneComponent* RootComponent = nullptr;
	bool bHasAutoGeneratedRootComponent = false;

	FVector PendingActorLocation = FVector(0, 0, 0);
	bool bVisible = true;
	bool bLockActorMovement = false;
	FString FolderPath;
	// TODO: 임시 프로토타입용 Tag입니다.
	// 장기적으로는 GameplayTag 또는 Editor Property 기반 식별 방식으로 교체해야 합니다.
	FString Tag;

	TArray<UActorComponent*> OwnedComponents;

	// 렌더링용 캐시
	mutable TArray<UPrimitiveComponent*> PrimitiveCache;
	mutable bool bPrimitiveCacheDirty = true;
	bool bQueuedForPartitionUpdate = false;
	bool bActorHasBegunPlay = false;

protected:
	bool bIsOverlappingDirty = false;
	bool bIsSelected = false;
};
