#include "PCH/LunaticPCH.h"
#include "GameFramework/AActor.h"
#include "Object/ObjectFactory.h"
#include "Component/PrimitiveComponent.h"
#include "Component/ActorComponent.h"
#include "Component/BillboardComponent.h"
#include "Component/Movement/MovementComponent.h"
#include "Component/SkinnedMeshComponent.h"
#include "Component/StaticMeshComponent.h"
#include "Component/TextRenderComponent.h"
#include "Math/Rotator.h"
#include "GameFramework/Level.h"
#include "GameFramework/World.h"
#include "Serialization/Archive.h"
#include "Engine/Runtime/Engine.h"
#include "Resource/ResourceManager.h"
#include "Texture/Texture2D.h"

#include <algorithm>

IMPLEMENT_CLASS(AActor, UObject)

namespace
{
const char* GetDefaultEditorBillboardIconKey(const AActor* Actor)
{
	if (!Actor)
	{
		return "Editor.Icon.Actor";
	}

	const FString ClassName = Actor->GetClass()->GetName();
	if (ClassName.find("Character") != FString::npos)
	{
		return "Editor.Icon.Character";
	}
	if (ClassName.find("Pawn") != FString::npos)
	{
		return "Editor.Icon.Pawn";
	}
	if (ClassName.find("Camera") != FString::npos)
	{
		return "Editor.Icon.Camera";
	}
	if (ClassName.find("SpotLight") != FString::npos)
	{
		return "Editor.Icon.SpotLight";
	}
	if (ClassName.find("PointLight") != FString::npos)
	{
		return "Editor.Icon.PointLight";
	}
	if (ClassName.find("DirectionalLight") != FString::npos)
	{
		return "Editor.Icon.DirectionalLight";
	}
	if (ClassName.find("AmbientLight") != FString::npos)
	{
		return "Editor.Icon.AmbientLight";
	}
	if (ClassName.find("HeightFog") != FString::npos)
	{
		return "Editor.Icon.HeightFog";
	}
	if (ClassName.find("Decal") != FString::npos)
	{
		return "Editor.Icon.Decal";
	}
	if (ClassName.find("StaticMeshActor") != FString::npos)
	{
		return "Editor.Icon.StaticMeshActor";
	}
	if (ClassName.find("SkeletalMeshActor") != FString::npos)
	{
		return "Editor.Icon.SkeletalMeshActor";
	}
	if (ClassName.find("ScreenText") != FString::npos)
	{
		return "Editor.Icon.ScreenText";
	}
	if (ClassName.find("WorldText") != FString::npos)
	{
		return "Editor.Icon.ScreenText";
	}

	if (const USceneComponent* RootComponent = Actor->GetRootComponent())
	{
		if (RootComponent->IsA<UStaticMeshComponent>())
		{
			return "Editor.Icon.StaticMeshActor";
		}
	}

	return "Editor.Icon.Actor";
}

bool ActorHasVisibleStaticMesh(const AActor* Actor)
{
	if (!Actor)
	{
		return false;
	}

	for (UActorComponent* Component : Actor->GetComponents())
	{
		UStaticMeshComponent* StaticMeshComponent = Cast<UStaticMeshComponent>(Component);
		if (StaticMeshComponent && StaticMeshComponent->IsVisible() && StaticMeshComponent->GetStaticMesh())
		{
			return true;
		}
	}

	return false;
}

bool ActorHasVisibleSkeletalMesh(const AActor* Actor)
{
	if (!Actor)
	{
		return false;
	}

	for (UActorComponent* Component : Actor->GetComponents())
	{
		USkinnedMeshComponent* SkinnedMeshComponent = Cast<USkinnedMeshComponent>(Component);
		if (SkinnedMeshComponent && SkinnedMeshComponent->IsVisible() && SkinnedMeshComponent->GetSkeletalMesh())
		{
			return true;
		}
	}

	return false;
}

bool ActorNeedsEditorBillboardFallback(const AActor* Actor)
{
	return !ActorHasVisibleStaticMesh(Actor) && !ActorHasVisibleSkeletalMesh(Actor);
}
}

UBillboardComponent* AActor::FindEditorOnlyBillboardComponent() const
{
	for (UActorComponent* Component : OwnedComponents)
	{
		UBillboardComponent* BillboardComponent = Cast<UBillboardComponent>(Component);
		if (BillboardComponent && BillboardComponent->IsEditorOnlyComponent())
		{
			return BillboardComponent;
		}
	}

	return nullptr;
}

bool AActor::HasNonEditorOnlyPrimitiveComponent() const
{
	for (UActorComponent* Component : OwnedComponents)
	{
		UPrimitiveComponent* PrimitiveComponent = Cast<UPrimitiveComponent>(Component);
		if (PrimitiveComponent && !PrimitiveComponent->IsEditorOnlyComponent())
		{
			// Actor helper billboard는 "보일 만한 mesh가 있느냐"가 아니라
			// "실제 primitive component가 존재하느냐"를 기준으로 숨긴다.
			// StaticMesh/SkeletalMesh 데이터가 아직 비어 있어도 primitive가 있으면
			// 해당 component의 렌더/피킹 책임을 우선한다.
			return true;
		}
	}

	return false;
}

AActor::AActor()
{
	PrimaryActorTick.SetTarget(this);
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bTickEnabled = true;
	PrimaryActorTick.bStartWithTickEnabled = true;

	if (USceneComponent* DefaultRootComponent = AddComponent<USceneComponent>())
	{
		DefaultRootComponent->SetCanDeleteFromDetails(false);
		RootComponent = DefaultRootComponent;
		bHasAutoGeneratedRootComponent = true;
	}
}
AActor::~AActor()
{
	PrimaryActorTick.UnRegisterTickFunction();

	// 계층 구조 파괴 시 OwnedComponents가 재귀적으로 수정되므로
	// 리스트가 비워질 때까지 뒤에서부터 하나씩 제거
	// (Iterator Invalidation 방지)
	while (!OwnedComponents.empty())
	{
		UActorComponent* Comp = OwnedComponents.back();
		// OwnedComponents.erase()는 RemoveComponent 내부에서 실행되므로 따로 해 줄 필요 없음
		RemoveComponent(Comp);
	}

	RootComponent = nullptr;
}


UActorComponent* AActor::AddComponentByClass(UClass* Class)
{
	if (!Class) return nullptr;

	UObject* Obj = FObjectFactory::Get().Create(Class->GetName(), this);
	if (!Obj) return nullptr;

	UActorComponent* Comp = Cast<UActorComponent>(Obj);
	if (!Comp) {
		UObjectManager::Get().DestroyObject(Obj);
		return nullptr;
	}

	Comp->SetOwner(this);
	OwnedComponents.push_back(Comp);
	bPrimitiveCacheDirty = true;
	Comp->CreateRenderState();
	MarkPickingDirty();
	SyncEditorBillboardVisibility();
	return Comp;
}

void AActor::RegisterComponent(UActorComponent* Comp)
{
	if (!Comp) return;

	auto it = std::find(OwnedComponents.begin(), OwnedComponents.end(), Comp);
	if (it == OwnedComponents.end()) {
		Comp->SetOwner(this);
		Comp->SetOuter(this);
		OwnedComponents.push_back(Comp);
		bPrimitiveCacheDirty = true;
		MarkPickingDirty();
		Comp->CreateRenderState();
		SyncEditorBillboardVisibility();
	}
}

void AActor::RemoveComponent(UActorComponent* Component)
{
	if (!Component) return;

	USceneComponent* RemovedSceneComponent = Cast<USceneComponent>(Component);
	if (RemovedSceneComponent)
	{
		for (UActorComponent* ExistingComponent : OwnedComponents)
		{
			UMovementComponent* MovementComponent = Cast<UMovementComponent>(ExistingComponent);
			if (MovementComponent && ExistingComponent != Component)
			{
				MovementComponent->ClearUpdatedComponentIfMatches(RemovedSceneComponent);
			}
		}
	}

	Component->PrimaryComponentTick.UnRegisterTickFunction();

	// PrimitiveComponent::DestroyRenderState 가 Scene/Partition/PickingBVH/VisibleSet
	// 정리를 모두 책임지므로 여기서는 단순히 호출만 한다.
	Component->DestroyRenderState();

	auto it = std::find(OwnedComponents.begin(), OwnedComponents.end(), Component);
	if (it != OwnedComponents.end()) {
		OwnedComponents.erase(it);
		bPrimitiveCacheDirty = true;
		MarkPickingDirty();
	}

	// RootComponent가 제거되면 nullptr로
	if (RootComponent == Component)
		RootComponent = nullptr;

	SyncEditorBillboardVisibility();
	UObjectManager::Get().DestroyObject(Component);
}

void AActor::SetRootComponent(USceneComponent* Comp)
{
	if (!Comp) return;

	if (RootComponent == Comp)
	{
		return;
	}

	USceneComponent* PreviousRootComponent = RootComponent;
	const bool bReplaceAutoGeneratedRoot = bHasAutoGeneratedRootComponent
		&& PreviousRootComponent
		&& PreviousRootComponent != Comp;

	if (bReplaceAutoGeneratedRoot)
	{
		if (Comp->GetParent() == PreviousRootComponent)
		{
			Comp->SetParent(nullptr);
		}

		const TArray<USceneComponent*> PreviousChildren = PreviousRootComponent->GetChildren();
		for (USceneComponent* ChildComponent : PreviousChildren)
		{
			if (!ChildComponent || ChildComponent == Comp)
			{
				continue;
			}

			ChildComponent->AttachToComponent(Comp);
		}
	}

	RootComponent = Comp;
	bHasAutoGeneratedRootComponent = false;

	if (bReplaceAutoGeneratedRoot)
	{
		RemoveComponent(PreviousRootComponent);
	}
}

void AActor::EnsureEditorBillboardForActor()
{
	UBillboardComponent* BillboardComponent = FindEditorOnlyBillboardComponent();
	if (!BillboardComponent && HasNonEditorOnlyPrimitiveComponent() && !ActorNeedsEditorBillboardFallback(this))
	{
		return;
	}

	if (!BillboardComponent)
	{
		BillboardComponent = AddComponent<UBillboardComponent>();
		if (!BillboardComponent)
		{
			return;
		}
	}

	BillboardComponent->SetCanDeleteFromDetails(false);
	BillboardComponent->SetEditorOnlyComponent(true);
	BillboardComponent->SetHiddenInComponentTree(true);
	BillboardComponent->SetAbsoluteScale(true);
	BillboardComponent->SetSpriteSize(1.0f, 1.0f);

	if (!RootComponent)
	{
		SetRootComponent(BillboardComponent);
	}
	else if (BillboardComponent != RootComponent && BillboardComponent->GetParent() == nullptr)
	{
		BillboardComponent->AttachToComponent(RootComponent);
	}

	if (BillboardComponent->GetTexture() == nullptr)
	{
		const FString& TexturePath = BillboardComponent->GetTexturePath();
		if (!TexturePath.empty() && TexturePath != "None")
		{
			BillboardComponent->PostEditProperty("Texture");
		}
	}

	if (BillboardComponent->GetTexture() == nullptr)
	{
		ID3D11Device* Device = GEngine ? GEngine->GetRenderer().GetFD3DDevice().GetDevice() : nullptr;
		const FString IconTexturePath = FResourceManager::Get().ResolvePath(FName(GetDefaultEditorBillboardIconKey(this)));
		if (UTexture2D* Texture = UTexture2D::LoadFromFile(IconTexturePath, Device))
		{
			BillboardComponent->SetTexture(Texture);
		}
	}

	SyncEditorBillboardVisibility();
}

void AActor::SyncEditorBillboardVisibility()
{
	UBillboardComponent* BillboardComponent = FindEditorOnlyBillboardComponent();
	if (!BillboardComponent)
	{
		return;
	}

	const bool bShouldShowBillboard =
		!HasNonEditorOnlyPrimitiveComponent() || ActorNeedsEditorBillboardFallback(this);
	BillboardComponent->SetVisibility(bShouldShowBillboard);
}

UWorld* AActor::GetWorld() const
{
	return GetTypedOuter<UWorld>();
}

ULevel* AActor::GetLevel() const
{
	return GetTypedOuter<ULevel>();
}

void AActor::SetVisible(bool Visible)
{
	if (bVisible == Visible)
	{
		return;
	}

	bVisible = Visible;
	// 각 PrimitiveComponent가 자신의 dirty 시퀀스(Proxy/Octree/PickingBVH/VisibleSet)를
	// 전파하면 액터 단위 캐시도 자연히 무효화된다.
	for (UPrimitiveComponent* Prim : GetPrimitiveComponents())
	{
		if (Prim)
		{
			Prim->MarkRenderVisibilityDirty();
		}
	}
}

void AActor::MarkPickingDirty()
{
	if (UWorld* World = GetWorld())
	{
		World->MarkWorldPrimitivePickingBVHDirty();
	}
}

FVector AActor::GetActorLocation() const
{
	if (RootComponent)
	{
		return RootComponent->GetWorldLocation();
	}
	return FVector(0, 0, 0);
}

void AActor::SetActorLocation(const FVector& NewLocation)
{
	if (bLockActorMovement)
	{
		return;
	}

	PendingActorLocation = NewLocation;

	if (RootComponent)
	{
		RootComponent->SetWorldLocation(NewLocation);
	}
}

void AActor::AddActorWorldOffset(const FVector& Delta)
{
	if (bLockActorMovement)
	{
		return;
	}

	if (RootComponent)
	{
		RootComponent->AddWorldOffset(Delta);
	}
}

void AActor::BeginPlay()
{
	// 재진입 방지 — UE의 HasActorBegunPlay() 가드 대응.
	if (bActorHasBegunPlay) return;
	bActorHasBegunPlay = true;

	// UE 순서: 컴포넌트 BeginPlay 먼저, 그다음 Actor 본인 (오버라이드 측 Super 호출 시).
	for (UActorComponent* Comp : OwnedComponents)
	{
		if (Comp) Comp->BeginPlay();
	}
}

//엔진 단계에서의 틱
void AActor::TickActor(float DeltaSeconds, ELevelTick TickType, FActorTickFunction& ThisTickFunction)
{
	if (GetWorld())
	{
		//유저 코드 
		Tick(DeltaSeconds);	
	}
}

void AActor::EndPlay()
{
	if (!bActorHasBegunPlay) return;
	bActorHasBegunPlay = false;
	PrimaryActorTick.UnRegisterTickFunction();

	for (UActorComponent* Comp : OwnedComponents)
	{
		if (Comp)
		{
			Comp->PrimaryComponentTick.UnRegisterTickFunction();
			Comp->EndPlay();
		}
	}
}

void AActor::Tick(float DeltaTime)
{
	/*for (UActorComponent* ActorComp : OwnedComponents)
	{
		ActorComp->Tick(DeltaTime);
	}*/
}

FRotator AActor::GetActorRotation() const
{
	return RootComponent ? RootComponent->GetRelativeRotation() : FRotator();
}

void AActor::SetActorRotation(const FRotator& NewRotation)
{
	if (bLockActorMovement)
	{
		return;
	}

	if (RootComponent)
	{
		RootComponent->SetRelativeRotation(NewRotation);
	}
}

void AActor::SetActorRotation(const FVector& EulerRotation)
{
	if (bLockActorMovement)
	{
		return;
	}

	if (RootComponent)
	{
		RootComponent->SetRelativeRotation(EulerRotation);
	}
}

FVector AActor::GetActorScale() const
{
	return RootComponent ? RootComponent->GetRelativeScale() : FVector(1, 1, 1);
}

void AActor::SetActorScale(const FVector& NewScale)
{
	if (bLockActorMovement)
	{
		return;
	}

	if (RootComponent)
	{
		RootComponent->SetRelativeScale(NewScale);
	}
}

FVector AActor::GetActorForward() const
{
	if (RootComponent)
	{
		return RootComponent->GetForwardVector();
	}

	return FVector(0, 0, 1);
}
// this actor base calculate camera view
// if have cameraComponent use cameraComp view
// If not present 
// fallback to the Actor's own Location,Rotation
#include "Component/CameraComponent.h"
void AActor::CalcCamera(float DeltaTime, FMinimalViewInfo& OutResult)
{
	if (UCameraComponent* CameraComponent = GetComponentByClass<UCameraComponent>())
	{
		CameraComponent->GetCameraView(DeltaTime, OutResult);
		return;
	}
	OutResult.Location = GetActorLocation();
	OutResult.Rotation = GetActorRotation();
	OutResult.FOV = 3.14159265358979f / 3.0f;
	OutResult.NearZ = 0.1f;
	OutResult.FarZ = 1000.0f;
	OutResult.bIsOrthogonal = false;
	OutResult.OrthoWidth = 10.0f;
	OutResult.PostProcessBlendWeight = 1.0f;
}

void AActor::Serialize(FArchive& Ar)
{
	UObject::Serialize(Ar);
	// 소유 포인터(OwnedComponents/RootComponent/Outer)는 직렬화 제외 — 복제 단계에서 재구성.
	Ar << bVisible;
	Ar << bNeedsTick;
	Ar << FolderPath;
}

// SceneComponent 서브트리를 재귀 복제. 부모 → 자식 순으로 만들되,
// RegisterComponent(=CreateRenderState/Proxy) 호출 전에 부모에 Attach 해서
// 프록시가 처음부터 올바른 월드 트랜스폼으로 생성되도록 한다.
// (Attach 전 Register 시 child의 world transform = local로 잘못 계산되어
//  복제 직후 한 프레임 동안 잘못된 위치에 렌더되는 문제가 있었음.)
static USceneComponent* DuplicateSceneSubtree(
	const USceneComponent* Src,
	AActor* DupOwner,
	USceneComponent* DupParent,
	TSet<const UActorComponent*>& Visited)
{
	if (!Src) return nullptr;

	USceneComponent* DupNode = Cast<USceneComponent>(Src->Duplicate(DupOwner));
	if (!DupNode) return nullptr;

	DupNode->SetFName(Src->GetFName());
	DupNode->SetOwner(DupOwner);
	if (DupParent)
	{
		DupNode->AttachToComponent(DupParent); // Register 전에 부모 연결
	}
	DupOwner->RegisterComponent(DupNode); // Outer/OwnedComponents/CreateRenderState 일괄 처리
	Visited.insert(Src);

	for (USceneComponent* Child : Src->GetChildren())
	{
		DuplicateSceneSubtree(Child, DupOwner, DupNode, Visited);
	}
	return DupNode;
}

UObject* AActor::Duplicate(UObject* NewOuter) const
{
	// 1) 같은 타입 액터를 팩토리로 생성 (UObject::Duplicate 경유: Serialize 왕복까지 수행)
	//    NewOuter 미지정 시 원본의 Outer를 승계하고, 에디터 Ctrl+D 호환을 위해 아래에서 자동 등록한다.
	UObject* DupBase = UObject::Duplicate(NewOuter);
	AActor* Dup = static_cast<AActor*>(DupBase);
	if (!Dup)
	{
		return nullptr;
	}

	Dup->SetFName(GetFName());

	// 2) 얕은 복사로 따라온 컴포넌트 컨테이너 즉시 비우기 (안전장치)
	Dup->OwnedComponents.clear();
	Dup->RootComponent = nullptr;
	Dup->bPrimitiveCacheDirty = true;

	TSet<const UActorComponent*> Visited;

	// 3a) Root 서브트리 재귀 복제 — 도달 가능한 모든 SceneComponent를 처리
	if (RootComponent)
	{
		USceneComponent* DupRoot = DuplicateSceneSubtree(RootComponent, Dup, nullptr, Visited);
		if (DupRoot)
		{
			Dup->SetRootComponent(DupRoot);
		}
	}

	// 3b) 트리에 포함되지 않은 나머지(비씬 컴포넌트 + 분리된 씬 컴포넌트) 평면 복제
	for (UActorComponent* Comp : OwnedComponents)
	{
		if (!Comp || Visited.count(Comp)) continue;

		UActorComponent* DupComp = Cast<UActorComponent>(Comp->Duplicate(Dup));
		if (!DupComp) continue;

		DupComp->SetFName(Comp->GetFName());
		DupComp->SetOwner(Dup);
		Dup->RegisterComponent(DupComp);
		Visited.insert(Comp);
	}

	Dup->bPrimitiveCacheDirty = true;

	// 4) 에디터 단일 액터 복제(Duplicate(nullptr))만 기존처럼 즉시 월드에 등록한다.
	//    Level/PIE 복제처럼 NewOuter가 명시된 경우에는 호출자가 대상 레벨에 등록해야 한다.
	if (!NewOuter)
	{
		if (UWorld* DestWorld = Dup->GetWorld())
		{
			DestWorld->AddActor(Dup);
		}
	}

	return Dup;
}

const TArray<UPrimitiveComponent*>& AActor::GetPrimitiveComponents() const
{
	if (bPrimitiveCacheDirty)
	{
		PrimitiveCache.clear();
		for (UActorComponent* Comp : OwnedComponents)
		{
			if (Comp && Comp->IsA<UPrimitiveComponent>())
			{
				PrimitiveCache.emplace_back(static_cast<UPrimitiveComponent*>(Comp));
			}
		}
		bPrimitiveCacheDirty = false;
	}
	return PrimitiveCache;
}

bool AActor::IsOverlappingActor(const AActor* Other) const {
	for (UActorComponent* OwnedComp : OwnedComponents) {
		if (UPrimitiveComponent* PrimComp = Cast<UPrimitiveComponent>(OwnedComp)) {
			if ((PrimComp->GetOverlapInfos().size() > 0) && PrimComp->IsOverlappingActor(Other)) {
				return true;
			}
		}
	}

	return false;
}
