[PreloadAssets]
; Primitive meshes
+Paths=/Content/Mesh/Primitive/cone.obj
+Paths=/Content/Mesh/Primitive/cube.obj
+Paths=/Content/Mesh/Primitive/cylinder.obj
+Paths=/Content/Mesh/Primitive/quad.obj
+Paths=/Content/Mesh/Primitive/ring.obj
+Paths=/Content/Mesh/Primitive/sphere.obj
+Paths=/Content/Mesh/Primitive/triangle.obj

; Sample materials
+Paths=/Content/Material/sample/brick.mtl
+Paths=/Content/Material/sample/metal.mtl
+Paths=/Content/Material/sample/multi-material.mtl
+Paths=/Content/Material/sample/wood.mtl

; Sample fonts
+Paths=/Content/Font/JetBrainsMono/JetBrainsMono_Medium.font.json