#include "LuaBlueprint/LuaBlueprintCompiler.h"

#include "LuaBlueprint/LuaBlueprintAsset.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <sstream>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace
{
    FString EscapeLuaString(const FString& In)
    {
        FString Out;
        Out.reserve(In.size() + 8);
        for (char Ch : In)
        {
            switch (Ch)
            {
            case '\\':
                Out += "\\\\";
                break;
            case '"':
                Out += "\\\"";
                break;
            case '\n':
                Out += "\\n";
                break;
            case '\r':
                Out += "\\r";
                break;
            case '\t':
                Out += "\\t";
                break;
            default:
                Out += Ch;
                break;
            }
        }
        return Out;
    }

    FString LuaQuoted(const FString& In)
    {
        return FString("\"") + EscapeLuaString(In) + "\"";
    }

    FString LuaName(const FName& Name)
    {
        return Name == FName::None ? FString() : Name.ToString();
    }

    const FLuaBlueprintPin* FindPinByName(const FLuaBlueprintNode& Node, const char* Name, ELuaBlueprintPinKind Kind)
    {
        for (const FLuaBlueprintPin& Pin : Node.Pins)
        {
            if (Pin.Kind == Kind && Pin.DisplayName.ToString() == Name)
            {
                return &Pin;
            }
        }
        return nullptr;
    }

    const FLuaBlueprintPin* FindFirstExecOutput(const FLuaBlueprintNode& Node)
    {
        for (const FLuaBlueprintPin& Pin : Node.Pins)
        {
            if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type == ELuaBlueprintPinType::Exec)
            {
                return &Pin;
            }
        }
        return nullptr;
    }

    const FLuaBlueprintPin* FindFirstValueOutput(const FLuaBlueprintNode& Node)
    {
        for (const FLuaBlueprintPin& Pin : Node.Pins)
        {
            if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type != ELuaBlueprintPinType::Exec)
            {
                return &Pin;
            }
        }
        return nullptr;
    }

    void AddDiagnostic(
        FLuaBlueprintCompileResult&     Result,
        ELuaBlueprintDiagnosticSeverity Severity,
        uint32                          NodeId,
        const FString&                  Message
        )
    {
        FLuaBlueprintDiagnostic Diagnostic;
        Diagnostic.Severity = Severity;
        Diagnostic.NodeId   = NodeId;
        Diagnostic.Message  = Message;
        Result.Diagnostics.push_back(std::move(Diagnostic));
        if (Severity == ELuaBlueprintDiagnosticSeverity::Error)
        {
            Result.bSuccess = false;
        }
    }

    class FCompilerContext
    {
    public:
        FCompilerContext(const ULuaBlueprintAsset& InAsset, FLuaBlueprintCompileResult& InResult)
            : Asset(InAsset), Result(InResult)
        {
            Result.bSuccess = true;
        }

        FString Compile()
        {
            ValidateGraph();

            std::ostringstream Out;
            Out << "-- Generated by Lua Blueprint compiler. Do not edit runtime output directly.\n";
            Out << "__vars = __vars or {}\n";
            EmitRuntimeHelpers(Out);
            EmitEventMetadata(Out);
            EmitVariableInitializers(Out);
            Out << "\n";

            EmitEventFunction(Out, ELuaBlueprintNodeType::EventBeginPlay, "BeginPlay", "");
            EmitEventFunction(Out, ELuaBlueprintNodeType::EventTick, "Tick", "DeltaTime");
            EmitEventFunction(Out, ELuaBlueprintNodeType::EventEndPlay, "EndPlay", "");
            EmitEventFunction(
                Out,
                ELuaBlueprintNodeType::EventOverlap,
                "OnOverlap",
                "OtherActor, OverlappedComponent, OtherComp"
            );
            EmitEventFunction(
                Out,
                ELuaBlueprintNodeType::EventEndOverlap,
                "OnEndOverlap",
                "OtherActor, OverlappedComponent, OtherComp"
            );
            EmitEventFunction(
                Out,
                ELuaBlueprintNodeType::EventHit,
                "OnHit",
                "OtherActor, HitComponent, OtherComp, NormalImpulse, HitResult"
            );
            EmitEventFunction(
                Out,
                ELuaBlueprintNodeType::EventEndHit,
                "OnEndHit",
                "OtherActor, HitComponent, OtherComp"
            );
            EmitCustomEventFunctions(Out);

            return Out.str();
        }

        // Loop body 가 자기 자신을 통해 다시 들어오는 (Branch 의 True 가 같은 노드로) 시각적 cycle 은
        // 정상이지만, 실제 데이터 cycle 은 막아야 한다. ExecStack 으로 호출 stack 만 추적하면
        // 같은 노드를 서로 다른 path 로 emit 할 때 false-positive 가 난다 — 매 호출마다 입력 시 push,
        // 출력 시 pop 으로 충분히 처리됨.

    private:
        void EmitVariableInitializers(std::ostringstream& Out)
        {
            for (const FLuaBlueprintVariable& Variable : Asset.GetVariables())
            {
                const FString Name = LuaName(Variable.Name);
                if (Name.empty())
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Warning,
                        0,
                        "Variable with empty name was skipped"
                    );
                    continue;
                }
                if (Variable.Type == ELuaBlueprintPinType::Object)
                {
                    Out << "if BP_InitVar then BP_InitVar(" << LuaQuoted(Name) << ", " << (Variable.bStrongObject
                        ? "true" : "false") << ") end\n";
                }
                else
                {
                    Out << "if __vars[" << LuaQuoted(Name) << "] == nil then __vars[" << LuaQuoted(Name) << "] = " <<
                    LiteralForVariable(Variable) << " end\n";
                }
            }
        }

        FString LiteralForVariable(const FLuaBlueprintVariable& Variable) const
        {
            switch (Variable.Type)
            {
            case ELuaBlueprintPinType::Bool:
                return Variable.BoolValue ? "true" : "false";
            case ELuaBlueprintPinType::Int:
                return std::to_string(Variable.IntValue);
            case ELuaBlueprintPinType::Float:
                return FormatFloat(Variable.FloatValue);
            case ELuaBlueprintPinType::String:
                return LuaQuoted(Variable.StringValue);
            case ELuaBlueprintPinType::Vector:
                return FormatVector(Variable.VectorValue);
            case ELuaBlueprintPinType::Object:
                return "nil";
            case ELuaBlueprintPinType::Array:
                return "{}";
            default:
                return "nil";
            }
        }

        void EmitEventFunction(
            std::ostringstream&   Out,
            ELuaBlueprintNodeType EventType,
            const char*           FunctionName,
            const char*           Args
            )
        {
            const FLuaBlueprintNode* Event = FindFirstNodeOfType(EventType);
            if (!Event || !HasConnectedExecOutput(*Event))
            {
                return;
            }

            Out << "function " << FunctionName << "(" << Args << ")\n";
            std::unordered_set<uint32> ExecStack;
            if (const FLuaBlueprintPin* Then = FindFirstExecOutput(*Event))
            {
                EmitNextExecFromPin(Out, Then->PinId, 1, ExecStack);
            }
            Out << "end\n\n";
        }

        void EmitCustomEventFunctions(std::ostringstream& Out)
        {
            for (const FLuaBlueprintNode& Node : Asset.GetNodes())
            {
                if (Node.Type != ELuaBlueprintNodeType::CustomEvent)
                {
                    continue;
                }
                const FString EventName = LuaName(Node.NameValue);
                if (EventName.empty())
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "CustomEvent has no name");
                    continue;
                }
                // CallCustomEvent 가 항상 모든 Arg slot 을 넘기므로 함수 signature 도 고정.
                // pin 이름과 동일하게 두면 GetOutputExpression 이 그대로 reference 가능.
                Out << "function " << CustomEventFunctionName(EventName) << "(Arg0, Arg1, Arg2, Arg3)\n";
                std::unordered_set<uint32> ExecStack;
                if (const FLuaBlueprintPin* Then = FindFirstExecOutput(Node))
                {
                    EmitNextExecFromPin(Out, Then->PinId, 1, ExecStack);
                }
                Out << "end\n\n";
            }
        }

        FString CustomEventFunctionName(const FString& EventName) const
        {
            FString Safe = "BP_Custom_";
            for (char Ch : EventName)
            {
                if ((Ch >= 'a' && Ch <= 'z') || (Ch >= 'A' && Ch <= 'Z') || (Ch >= '0' && Ch <= '9') || Ch == '_')
                {
                    Safe += Ch;
                }
                else
                {
                    Safe += '_';
                }
            }
            return Safe;
        }

        const FLuaBlueprintNode* FindFirstNodeOfType(ELuaBlueprintNodeType Type) const
        {
            for (const FLuaBlueprintNode& Node : Asset.GetNodes())
            {
                if (Node.Type == Type) return &Node;
            }
            return nullptr;
        }

        bool HasNodeOfType(ELuaBlueprintNodeType Type) const
        {
            return FindFirstNodeOfType(Type) != nullptr;
        }

        bool HasConnectedExecOutput(const FLuaBlueprintNode& Node) const
        {
            if (const FLuaBlueprintPin* Then = FindFirstExecOutput(Node))
            {
                return Asset.FindFirstLinkFromOutput(Then->PinId) != nullptr;
            }
            return false;
        }

        bool HasRunnableEvent(ELuaBlueprintNodeType Type) const
        {
            const FLuaBlueprintNode* Node = FindFirstNodeOfType(Type);
            return Node && HasConnectedExecOutput(*Node);
        }

        bool IsEventNode(ELuaBlueprintNodeType Type) const
        {
            switch (Type)
            {
            case ELuaBlueprintNodeType::EventBeginPlay:
            case ELuaBlueprintNodeType::EventTick:
            case ELuaBlueprintNodeType::EventEndPlay:
            case ELuaBlueprintNodeType::EventOverlap:
            case ELuaBlueprintNodeType::EventEndOverlap:
            case ELuaBlueprintNodeType::EventHit:
            case ELuaBlueprintNodeType::EventEndHit:
                return true;
            default:
                return false;
            }
        }

        FString EventMetadataName(ELuaBlueprintNodeType Type) const
        {
            switch (Type)
            {
            case ELuaBlueprintNodeType::EventBeginPlay:
                return "BeginPlay";
            case ELuaBlueprintNodeType::EventTick:
                return "Tick";
            case ELuaBlueprintNodeType::EventEndPlay:
                return "EndPlay";
            case ELuaBlueprintNodeType::EventOverlap:
                return "OnOverlap";
            case ELuaBlueprintNodeType::EventEndOverlap:
                return "OnEndOverlap";
            case ELuaBlueprintNodeType::EventHit:
                return "OnHit";
            case ELuaBlueprintNodeType::EventEndHit:
                return "OnEndHit";
            default:
                return "";
            }
        }

        const FLuaBlueprintVariable* FindVariableByName(const FString& Name) const
        {
            for (const FLuaBlueprintVariable& Variable : Asset.GetVariables())
            {
                if (LuaName(Variable.Name) == Name)
                {
                    return &Variable;
                }
            }
            return nullptr;
        }

        void ValidateGraph()
        {
            std::unordered_set<FString> VariableNames;
            for (const FLuaBlueprintVariable& Variable : Asset.GetVariables())
            {
                const FString Name = LuaName(Variable.Name);
                if (Name.empty())
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Warning,
                        0,
                        "Variable with empty name will be ignored"
                    );
                    continue;
                }
                if (!VariableNames.insert(Name).second)
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Error,
                        0,
                        FString("Duplicate variable name: ") + Name
                    );
                }
            }

            std::unordered_set<ELuaBlueprintNodeType> EventTypes;
            std::unordered_set<FString> CustomEventNames;
            std::unordered_set<FString> CustomEventFunctionNames;

            for (const FLuaBlueprintNode& Node : Asset.GetNodes())
            {
                if (Node.Type != ELuaBlueprintNodeType::CustomEvent)
                {
                    continue;
                }

                const FString EventName = LuaName(Node.NameValue);
                if (EventName.empty())
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "CustomEvent has no name");
                    continue;
                }
                if (!CustomEventNames.insert(EventName).second)
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, FString("Duplicate custom event: ") + EventName);
                }

                const FString FunctionName = CustomEventFunctionName(EventName);
                if (!CustomEventFunctionNames.insert(FunctionName).second)
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, FString("Custom event Lua function name collides after sanitizing: ") + EventName);
                }
            }

            for (const FLuaBlueprintNode& Node : Asset.GetNodes())
            {
                if (IsEventNode(Node.Type) && !EventTypes.insert(Node.Type).second)
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Error,
                        Node.NodeId,
                        FString("Duplicate event node: ") + EventMetadataName(Node.Type)
                    );
                }

                if (Node.Type == ELuaBlueprintNodeType::CallCustomEvent)
                {
                    const FString EventName = LuaName(Node.NameValue);
                    if (EventName.empty())
                    {
                        AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "CallCustomEvent has no event name");
                    }
                    else if (CustomEventNames.find(EventName) == CustomEventNames.end())
                    {
                        AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, FString("CallCustomEvent target does not exist: ") + EventName);
                    }
                }

                if (Node.Type == ELuaBlueprintNodeType::GetVariable || Node.Type == ELuaBlueprintNodeType::SetVariable)
                {
                    const FString VarName = LuaName(Node.NameValue);
                    if (!VarName.empty() && !FindVariableByName(VarName))
                    {
                        AddDiagnostic(
                            Result,
                            ELuaBlueprintDiagnosticSeverity::Error,
                            Node.NodeId,
                            FString("Variable does not exist: ") + VarName
                        );
                    }
                }
            }

            for (const FLuaBlueprintLink& Link : Asset.GetLinks())
            {
                const FLuaBlueprintPin* From = Asset.FindPin(Link.FromPinId);
                const FLuaBlueprintPin* To   = Asset.FindPin(Link.ToPinId);
                if (!From || !To)
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, 0, "Link references a missing pin");
                    continue;
                }
                if (From->Kind != ELuaBlueprintPinKind::Output || To->Kind != ELuaBlueprintPinKind::Input)
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, 0, "Link direction is invalid");
                }
                else if (!ULuaBlueprintAsset::ArePinTypesCompatibleForLink(From->Type, To->Type))
                {
                    AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, To->OwningNodeId, "Link type is not convertible");
                }
            }
        }

        void EmitRuntimeHelpers(std::ostringstream& Out)
        {
            Out << "local __bp_loop_limit = 100000\n";
            Out <<
            "local function __bp_safe_div(a,b) if b == nil or b == 0 then return 0 end return (a or 0) / b end\n";
            Out <<
            "local function __bp_safe_idiv(a,b) if b == nil or b == 0 then return 0 end return math.floor((a or 0) / b) end\n";
            Out <<
            "local function __bp_safe_mod(a,b) if b == nil or b == 0 then return 0 end return (a or 0) % b end\n";
            Out << "local function __bp_safe_sqrt(v) v = v or 0; if v < 0 then return 0 end return math.sqrt(v) end\n";
            Out <<
            "local function __bp_safe_random_int(a,b) a = a or 0; b = b or a; if a > b then a, b = b, a end return math.random(a, b) end\n";
            Out <<
            "local function __bp_safe_random_float(a,b) a = a or 0; b = b or 1; if a > b then a, b = b, a end return a + math.random() * (b - a) end\n";
            Out <<
            "local function __bp_safe_norm(v) if v == nil or v:Length() <= 0.000001 then return Vector(0,0,0) end return v:Normalized() end\n";
            Out << "local function __bp_bool(v) return v == true end\n";
            Out << "local function __bp_to_bool(v) if type(v) == 'boolean' then return v end if type(v) == 'number' then return v ~= 0 end if type(v) == 'string' then return v ~= '' and v ~= 'false' and v ~= '0' end if type(v) == 'table' then return next(v) ~= nil end return v ~= nil end\n";
            Out << "local function __bp_to_float(v) if type(v) == 'number' then return v end if type(v) == 'boolean' then return v and 1 or 0 end if type(v) == 'string' then return tonumber(v) or 0 end return 0 end\n";
            Out << "local function __bp_to_int(v) return math.floor(__bp_to_float(v)) end\n";
            Out << "local function __bp_to_string(v) if v == nil then return '' end return tostring(v) end\n";
            Out << "local function __bp_to_vector(v) if v == nil then return Vector(0,0,0) end if type(v) == 'number' then return Vector(v,v,v) end if type(v) == 'string' then local x,y,z = string.match(v, '([%-%.%d]+)%s*,%s*([%-%.%d]+)%s*,%s*([%-%.%d]+)'); return Vector(tonumber(x) or 0, tonumber(y) or 0, tonumber(z) or 0) end return v end\n";
            Out << "local function __bp_to_array(v) if type(v) == 'table' then return v end if v == nil then return {} end return { v } end\n";
            Out <<
            "local function __bp_get_var(name) if BP_GetVar then local v = BP_GetVar(name); if v ~= nil then return v end end return __vars[name] end\n";
            Out <<
            "local function __bp_set_var(name, value) if BP_SetVar then BP_SetVar(name, value) else __vars[name] = value end end\n";
        }

        void EmitEventMetadata(std::ostringstream& Out)
        {
            Out << "__events = {";
            Out << " BeginPlay = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventBeginPlay) ? "true" : "false") << ",";
            Out << " Tick = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventTick) ? "true" : "false") << ",";
            Out << " EndPlay = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventEndPlay) ? "true" : "false") << ",";
            Out << " OnOverlap = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventOverlap) ? "true" : "false") << ",";
            Out << " OnEndOverlap = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventEndOverlap) ? "true" : "false") <<
            ",";
            Out << " OnHit = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventHit) ? "true" : "false") << ",";
            Out << " OnEndHit = " << (HasRunnableEvent(ELuaBlueprintNodeType::EventEndHit) ? "true" : "false") << " }\n";
        }

        void EmitNextExecFromPin(
            std::ostringstream&         Out,
            uint32                      OutputPinId,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FLuaBlueprintLink* Link = Asset.FindFirstLinkFromOutput(OutputPinId);
            if (!Link) return;

            const FLuaBlueprintPin* InputPin = Asset.FindPin(Link->ToPinId);
            if (!InputPin) return;

            const FLuaBlueprintNode* Node = Asset.FindNode(InputPin->OwningNodeId);
            if (!Node) return;

            EmitExecNode(Out, *Node, Indent, ExecStack);
        }

        void EmitExecNode(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            if (ExecStack.find(Node.NodeId) != ExecStack.end())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "Exec cycle detected");
                EmitIndent(Out, Indent);
                Out << "-- compile error: exec cycle detected at node " << Node.NodeId << "\n";
                return;
            }

            ExecStack.insert(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "-- NodeId: " << Node.NodeId << " " << LuaQuoted(Node.DisplayName.ToString()) << "\n";
            switch (Node.Type)
            {
            case ELuaBlueprintNodeType::Sequence:
                EmitSequence(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::Branch:
                EmitBranch(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::ForLoop:
                EmitForLoop(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::WhileLoop:
                EmitWhileLoop(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::PrintString:
                EmitIndent(Out, Indent);
                Out << "print(tostring(" << GetInputExpression(Node, "Text", LuaQuoted(Node.StringValue)) << "))\n";
                EmitThen(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::SetVariable:
                EmitSetVariable(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::SetProperty:
                EmitSetProperty(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::CallFunction:
            case ELuaBlueprintNodeType::CallFunctionSignature:
                EmitCallFunction(Out, Node, Indent, ExecStack);
                break;

            case ELuaBlueprintNodeType::SpawnActor:
                EmitSpawnActor(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::DestroyActor:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):Destroy() end");
                break;
            case ELuaBlueprintNodeType::SetActorLocation:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Location = {Value} end");
                break;
            case ELuaBlueprintNodeType::SetActorRotation:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Rotation = {Value} end");
                break;
            case ELuaBlueprintNodeType::SetActorScale:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}).Scale = {Value} end");
                break;
            case ELuaBlueprintNodeType::AddActorWorldOffset:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):AddWorldOffset({Value}) end");
                break;
            case ELuaBlueprintNodeType::ActorAddTag:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):AddTag({Tag}) end");
                break;
            case ELuaBlueprintNodeType::ActorRemoveTag:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Target} then ({Target}):RemoveTag({Tag}) end");
                break;
            case ELuaBlueprintNodeType::ActivateComponent:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):Activate() end");
                break;
            case ELuaBlueprintNodeType::DeactivateComponent:
                EmitSimpleCall(Out, Node, Indent, ExecStack, "if {Component} then ({Component}):Deactivate() end");
                break;
            case ELuaBlueprintNodeType::AddForce:
                EmitSimpleCall(
                    Out,
                    Node,
                    Indent,
                    ExecStack,
                    "if {Component} then ({Component}):AddForce({Vector}) end"
                );
                break;
            case ELuaBlueprintNodeType::AddTorque:
                EmitSimpleCall(
                    Out,
                    Node,
                    Indent,
                    ExecStack,
                    "if {Component} then ({Component}):AddTorque({Vector}) end"
                );
                break;
            case ELuaBlueprintNodeType::SetLinearVelocity:
                EmitSimpleCall(
                    Out,
                    Node,
                    Indent,
                    ExecStack,
                    "if {Component} then ({Component}):SetLinearVelocity({Velocity}) end"
                );
                break;
            case ELuaBlueprintNodeType::SetSimulatePhysics:
                EmitSimpleCall(
                    Out,
                    Node,
                    Indent,
                    ExecStack,
                    "if {Component} then ({Component}):SetSimulatePhysics({Simulate}) end"
                );
                break;

            case ELuaBlueprintNodeType::CallCustomEvent:
                EmitCallCustomEvent(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::Delay:
                EmitDelay(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::Cast:
                EmitCast(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::ForEachActorByClass:
                EmitForEachActor(Out, Node, Indent, ExecStack, /*bByClass*/true);
                break;
            case ELuaBlueprintNodeType::ForEachActorByTag:
                EmitForEachActor(Out, Node, Indent, ExecStack, /*bByClass*/false);
                break;
            case ELuaBlueprintNodeType::ForEachArray:
                EmitForEachArray(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::BindEvent:
                EmitBindEvent(Out, Node, Indent, ExecStack);
                break;
            case ELuaBlueprintNodeType::UnbindEvent:
                EmitUnbindEvent(Out, Node, Indent, ExecStack);
                break;

            default:
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Warning,
                    Node.NodeId,
                    "Node is not executable and was skipped"
                );
                EmitThen(Out, Node, Indent, ExecStack);
                break;
            }
            ExecStack.erase(Node.NodeId);
        }

        void EmitForLoop(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString First = GetInputExpression(Node, "First", "0");
            const FString Last  = GetInputExpression(Node, "Last", "0");
            const FString Guard = FString("__for_guard") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "local " << Guard << " = 0\n";
            EmitIndent(Out, Indent);
            Out << "for __i = " << First << ", " << Last << " do\n";
            EmitIndent(Out, Indent + 1);
            Out << Guard << " = " << Guard << " + 1\n";
            EmitIndent(Out, Indent + 1);
            Out << "if " << Guard << " > __bp_loop_limit then error(\"LuaBlueprint for-loop iteration limit exceeded at node " << Node.NodeId << "\") end\n";
            LoopIndexNodeIds[Node.NodeId] = "__i";
            if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
            }
            LoopIndexNodeIds.erase(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "end\n";
            if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
            }
        }

        void EmitWhileLoop(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString Guard = FString("__guard") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "local " << Guard << " = 0\n";
            EmitIndent(Out, Indent);
            Out << "while " << GetInputExpression(Node, "Condition", "false") << " do\n";
            EmitIndent(Out, Indent + 1);
            Out << Guard << " = " << Guard << " + 1\n";
            EmitIndent(Out, Indent + 1);
            Out << "if " << Guard <<
            " > __bp_loop_limit then error(\"LuaBlueprint while-loop iteration limit exceeded at node " << Node.NodeId
            << "\") end\n";
            if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
            }
            EmitIndent(Out, Indent);
            Out << "end\n";
            if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
            }
        }

        // SpawnActor 는 데이터 output("Actor") 도 있으므로 실행 시 local 에 결과를 보관 후 EmitThen.
        // 하류 노드의 GetOutputExpression 은 ExecLocals 에서 이 local 을 읽는다.
        void EmitSpawnActor(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString ClassName = LuaName(Node.NameValue);
            if (ClassName.empty())
            {
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Error,
                    Node.NodeId,
                    "SpawnActor has no class name"
                );
                return;
            }
            const FString Local = FString("__n") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "local " << Local << " = World.SpawnActor(" << LuaQuoted(ClassName) << ")\n";
            ExecLocals[Node.NodeId] = Local;
            EmitThen(Out, Node, Indent, ExecStack);
            ExecLocals.erase(Node.NodeId);
        }

        // {PinName} 형태의 placeholder 를 GetInputExpression 으로 치환해 한 줄짜리 statement 를 emit.
        // 단순 wrapper exec 노드 (DestroyActor, AddForce, SetActorLocation 등) 공통.
        void EmitSimpleCall(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack,
            const FString&              Template
            )
        {
            FString Line = Template;
            // 핀별로 {PinName} 치환. Exec/Object/Vector/Float/Bool 등 모두 대상.
            for (const FLuaBlueprintPin& Pin : Node.Pins)
            {
                if (Pin.Kind != ELuaBlueprintPinKind::Input) continue;
                if (Pin.Type == ELuaBlueprintPinType::Exec) continue;
                const FString PlaceholderToken = FString("{") + Pin.DisplayName.ToString() + "}";
                const FString Value            = GetInputExpression(Node, Pin.DisplayName.ToString().c_str(), "nil");
                // 단순 string replace — 같은 placeholder 가 여러 번 나올 수 있으므로 loop.
                size_t Pos = 0;
                while ((Pos = Line.find(PlaceholderToken, Pos)) != FString::npos)
                {
                    Line.replace(Pos, PlaceholderToken.size(), Value);
                    Pos += Value.size();
                }
            }
            EmitIndent(Out, Indent);
            Out << Line << "\n";
            EmitThen(Out, Node, Indent, ExecStack);
        }

        void EmitCallCustomEvent(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString EventName = LuaName(Node.NameValue);
            if (EventName.empty())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "CallCustomEvent has no event name");
                return;
            }
            EmitIndent(Out, Indent);
            const FString Fn = CustomEventFunctionName(EventName);
            const FString A0 = GetInputExpression(Node, "Arg0", "nil");
            const FString A1 = GetInputExpression(Node, "Arg1", "nil");
            const FString A2 = GetInputExpression(Node, "Arg2", "nil");
            const FString A3 = GetInputExpression(Node, "Arg3", "nil");
            Out << "if " << Fn << " then " << Fn << "(" << A0 << ", " << A1 << ", " << A2 << ", " << A3 << ") end\n";
            EmitThen(Out, Node, Indent, ExecStack);
        }

        // Reflection.BindEvent(target, "EventName", BP_Custom_<CallbackName>)
        // Node.NameValue = target event/function 이름, Node.StringValue = local CustomEvent 콜백 이름.
        void EmitBindEvent(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString EventName    = LuaName(Node.NameValue);
            const FString CallbackName = Node.StringValue;
            if (EventName.empty())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "BindEvent missing target event name");
                return;
            }
            if (CallbackName.empty())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "BindEvent missing local CustomEvent callback name");
                return;
            }
            const FString Local = FString("__bind") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            // 콜백이 정의되지 않은 경우(스크립트에서 해당 CustomEvent 가 없음) BindEvent 자체를 skip.
            const FString CallbackFn = CustomEventFunctionName(CallbackName);
            Out << "local " << Local << " = (" << CallbackFn << " ~= nil) and Reflection.BindEvent("
                << GetInputExpression(Node, "Target", "obj") << ", " << LuaQuoted(EventName)
                << ", " << CallbackFn << ") or false\n";
            ExecLocals[Node.NodeId] = Local;
            EmitThen(Out, Node, Indent, ExecStack);
            ExecLocals.erase(Node.NodeId);
        }

        void EmitUnbindEvent(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString EventName = LuaName(Node.NameValue);
            if (EventName.empty())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "UnbindEvent missing target event name");
                return;
            }
            EmitIndent(Out, Indent);
            Out << "Reflection.UnbindEvent(" << GetInputExpression(Node, "Target", "obj") << ", "
                << LuaQuoted(EventName) << ")\n";
            EmitThen(Out, Node, Indent, ExecStack);
        }

        void EmitDelay(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString Seconds = GetInputExpression(Node, "Seconds", "0");
            EmitIndent(Out, Indent);
            Out << "if BP_Delay then\n";
            EmitIndent(Out, Indent + 1);
            Out << "BP_Delay(" << Seconds << ", function()\n";
            EmitThen(Out, Node, Indent + 2, ExecStack);
            EmitIndent(Out, Indent + 1);
            Out << "end)\n";
            EmitIndent(Out, Indent);
            Out << "else\n";
            EmitIndent(Out, Indent + 1);
            Out << "-- No component-owned delay scheduler is available; skip unsafe global coroutine fallback.\n";
            EmitIndent(Out, Indent);
            Out << "end\n";
        }

        // Cast: Success/Failed exec 분기. Result 데이터 output 은 Success 경로에서만 유효.
        void EmitCast(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString ClassName = LuaName(Node.NameValue);
            if (ClassName.empty())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "Cast has no class name");
                return;
            }
            const FString Local = FString("__c") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "local " << Local << " = Reflection.Cast(" << GetInputExpression(Node, "Target", "nil") << ", " <<
            LuaQuoted(ClassName) << ")\n";

            EmitIndent(Out, Indent);
            Out << "if " << Local << " ~= nil then\n";
            ExecLocals[Node.NodeId] = Local;
            if (const FLuaBlueprintPin* Success = FindPinByName(Node, "Success", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Success->PinId, Indent + 1, ExecStack);
            }
            ExecLocals.erase(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "else\n";
            if (const FLuaBlueprintPin* Failed = FindPinByName(Node, "Failed", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Failed->PinId, Indent + 1, ExecStack);
            }
            EmitIndent(Out, Indent);
            Out << "end\n";
        }

        // ForEachActor — class 또는 tag 기반. iteration 동안 Actor pin/Index pin 매핑 set.
        void EmitForEachActor(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack,
            bool                        bByClass
            )
        {
            const FString Key = bByClass ? LuaName(Node.NameValue) : Node.StringValue;
            if (Key.empty())
            {
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Error,
                    Node.NodeId,
                    bByClass ? "ForEachActor has no class name" : "ForEachActor has no tag"
                );
                return;
            }
            const FString ActorLocal = FString("__a") + std::to_string(Node.NodeId);
            const FString IndexLocal = FString("__i") + std::to_string(Node.NodeId);
            const char*   Source     = bByClass ? "World.FindActorsByClass" : "World.FindActorsByTag";

            EmitIndent(Out, Indent);
            Out << "for " << IndexLocal << ", " << ActorLocal << " in ipairs(" << Source << "(" << LuaQuoted(Key) <<
            ")) do\n";
            ForEachActorNodeIds[Node.NodeId] = ActorLocal;
            LoopIndexNodeIds[Node.NodeId]    = IndexLocal;
            if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
            }
            ForEachActorNodeIds.erase(Node.NodeId);
            LoopIndexNodeIds.erase(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "end\n";
            if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
            }
        }

        void EmitForEachArray(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString ArrayExpr = GetInputExpression(Node, "Array", "{}");
            const FString ItemLocal = FString("__item") + std::to_string(Node.NodeId);
            const FString IndexLocal = FString("__idx") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "for " << IndexLocal << ", " << ItemLocal << " in ipairs(__bp_to_array(" << ArrayExpr << ")) do\n";
            ForEachActorNodeIds[Node.NodeId] = ItemLocal;
            LoopIndexNodeIds[Node.NodeId] = IndexLocal;
            if (const FLuaBlueprintPin* Loop = FindPinByName(Node, "Loop", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Loop->PinId, Indent + 1, ExecStack);
            }
            ForEachActorNodeIds.erase(Node.NodeId);
            LoopIndexNodeIds.erase(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "end\n";
            if (const FLuaBlueprintPin* Done = FindPinByName(Node, "Completed", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, Done->PinId, Indent, ExecStack);
            }
        }

        void EmitSequence(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            TArray<const FLuaBlueprintPin*> Outputs;
            for (const FLuaBlueprintPin& Pin : Node.Pins)
            {
                if (Pin.Kind == ELuaBlueprintPinKind::Output && Pin.Type == ELuaBlueprintPinType::Exec)
                {
                    Outputs.push_back(&Pin);
                }
            }
            std::sort(
                Outputs.begin(),
                Outputs.end(),
                [](const FLuaBlueprintPin* A, const FLuaBlueprintPin* B)
                {
                    return A->DisplayName.ToString() < B->DisplayName.ToString();
                }
            );
            for (const FLuaBlueprintPin* Pin : Outputs)
            {
                EmitNextExecFromPin(Out, Pin->PinId, Indent, ExecStack);
            }
        }

        void EmitBranch(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            EmitIndent(Out, Indent);
            Out << "if __bp_to_bool(" << GetInputExpression(Node, "Condition", "false") << ") then\n";
            if (const FLuaBlueprintPin* TruePin = FindPinByName(Node, "True", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, TruePin->PinId, Indent + 1, ExecStack);
            }
            EmitIndent(Out, Indent);
            Out << "else\n";
            if (const FLuaBlueprintPin* FalsePin = FindPinByName(Node, "False", ELuaBlueprintPinKind::Output))
            {
                EmitNextExecFromPin(Out, FalsePin->PinId, Indent + 1, ExecStack);
            }
            EmitIndent(Out, Indent);
            Out << "end\n";
        }

        void EmitSetVariable(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString VarName = LuaName(Node.NameValue);
            if (VarName.empty())
            {
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Error,
                    Node.NodeId,
                    "SetVariable has no variable name"
                );
                return;
            }

            const FLuaBlueprintVariable* Variable = FindVariableByName(VarName);
            EmitIndent(Out, Indent);
            if (Variable && Variable->Type == ELuaBlueprintPinType::Object)
            {
                Out << "__bp_set_var(" << LuaQuoted(VarName) << ", " << GetInputExpression(Node, "Value", "nil") <<
                ")\n";
            }
            else
            {
                Out << "__vars[" << LuaQuoted(VarName) << "] = " << GetInputExpression(Node, "Value", "nil") << "\n";
            }
            EmitThen(Out, Node, Indent, ExecStack);
        }

        void EmitSetProperty(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString PropertyName = LuaName(Node.NameValue);
            if (PropertyName.empty())
            {
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Error,
                    Node.NodeId,
                    "SetProperty has no property name"
                );
                return;
            }
            EmitIndent(Out, Indent);
            Out << "Reflection.SetProperty(" << GetInputExpression(Node, "Target", "obj") << ", " << LuaQuoted(
                PropertyName
            ) << ", " << GetInputExpression(Node, "Value", "nil") << ")\n";
            EmitThen(Out, Node, Indent, ExecStack);
        }

        void EmitCallFunction(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            const FString Target = GetInputExpression(Node, "Target", "obj");
            const FString Name   = (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
            ? (!Node.StringValue.empty() ? Node.StringValue : LuaName(Node.NameValue)) : LuaName(Node.NameValue);

            if (Name.empty())
            {
                AddDiagnostic(
                    Result,
                    ELuaBlueprintDiagnosticSeverity::Error,
                    Node.NodeId,
                    "CallFunction has no function name/signature"
                );
                return;
            }

            const FString Local = FString("__call") + std::to_string(Node.NodeId);
            EmitIndent(Out, Indent);
            Out << "local " << Local << " = " << MakeCallExpression(Node, Target, Name) << "\n";
            ExecLocals[Node.NodeId] = Local;
            EmitThen(Out, Node, Indent, ExecStack);
            ExecLocals.erase(Node.NodeId);
        }

        void EmitThen(
            std::ostringstream&         Out,
            const FLuaBlueprintNode&    Node,
            int                         Indent,
            std::unordered_set<uint32>& ExecStack
            )
        {
            if (const FLuaBlueprintPin* Then = FindFirstExecOutput(Node))
            {
                EmitNextExecFromPin(Out, Then->PinId, Indent, ExecStack);
            }
        }

        FString GetInputExpression(const FLuaBlueprintNode& Node, const char* PinName, const FString& DefaultExpr)
        {
            const FLuaBlueprintPin* InputPin = FindPinByName(Node, PinName, ELuaBlueprintPinKind::Input);
            if (!InputPin)
            {
                return DefaultExpr;
            }

            const FLuaBlueprintLink* Link = Asset.FindLinkToInput(InputPin->PinId);
            if (!Link)
            {
                // 연결이 없으면 핀의 inline literal 사용 (실제 Blueprint 동작).
                return PinDefaultExpression(*InputPin, DefaultExpr);
            }

            const FLuaBlueprintPin* SourcePin = Asset.FindPin(Link->FromPinId);
            if (!SourcePin)
            {
                return DefaultExpr;
            }

            const FLuaBlueprintNode* SourceNode = Asset.FindNode(SourcePin->OwningNodeId);
            if (!SourceNode)
            {
                return DefaultExpr;
            }

            const FString SourceExpr = GetOutputExpression(*SourceNode, *SourcePin);
            return ConvertExpression(SourceExpr, SourcePin->Type, InputPin->Type);
        }

        FString ConvertExpression(const FString& Expr, ELuaBlueprintPinType FromType, ELuaBlueprintPinType ToType) const
        {
            if (ToType == ELuaBlueprintPinType::Any || FromType == ToType)
            {
                return Expr;
            }
            if (FromType == ELuaBlueprintPinType::Any)
            {
                // Any source 는 input pin 의 요구 타입에 맞춰 안전 helper로 감싼다.
            }
            switch (ToType)
            {
            case ELuaBlueprintPinType::Bool:
                return FString("__bp_to_bool(") + Expr + ")";
            case ELuaBlueprintPinType::Int:
                return FString("__bp_to_int(") + Expr + ")";
            case ELuaBlueprintPinType::Float:
                return FString("__bp_to_float(") + Expr + ")";
            case ELuaBlueprintPinType::String:
                return FString("__bp_to_string(") + Expr + ")";
            case ELuaBlueprintPinType::Vector:
                return FString("__bp_to_vector(") + Expr + ")";
            case ELuaBlueprintPinType::Array:
                return FString("__bp_to_array(") + Expr + ")";
            default:
                return Expr;
            }
        }

        FString PinDefaultExpression(const FLuaBlueprintPin& Pin, const FString& Fallback) const
        {
            switch (Pin.Type)
            {
            case ELuaBlueprintPinType::Bool:
                return Pin.DefaultBool ? "true" : "false";
            case ELuaBlueprintPinType::Int:
                return std::to_string(Pin.DefaultInt);
            case ELuaBlueprintPinType::Float:
                return FormatFloat(Pin.DefaultFloat);
            case ELuaBlueprintPinType::String:
                return LuaQuoted(Pin.DefaultString);
            case ELuaBlueprintPinType::Vector:
                return FormatVector(Pin.DefaultVector);
            case ELuaBlueprintPinType::Object:
                return Fallback;
            case ELuaBlueprintPinType::Any:
            case ELuaBlueprintPinType::Exec: default:
                return Fallback;
            }
        }

        FString GetOutputExpression(const FLuaBlueprintNode& Node, const FLuaBlueprintPin& OutputPin)
        {
            if (DataStack.find(Node.NodeId) != DataStack.end())
            {
                AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Error, Node.NodeId, "Data pin cycle detected");
                return "nil";
            }

            DataStack.insert(Node.NodeId);
            FString Expr = BuildOutputExpression(Node, OutputPin);
            DataStack.erase(Node.NodeId);
            return Expr;
        }

        FString BuildOutputExpression(const FLuaBlueprintNode& Node, const FLuaBlueprintPin& OutputPin)
        {
            (void)OutputPin;
            switch (Node.Type)
            {
            case ELuaBlueprintNodeType::EventTick:
                return OutputPin.DisplayName.ToString() == "DeltaTime" ? FString("DeltaTime") : FString("nil");
            case ELuaBlueprintNodeType::EventOverlap:
            case ELuaBlueprintNodeType::EventEndOverlap:
            case ELuaBlueprintNodeType::EventHit:
            case ELuaBlueprintNodeType::EventEndHit:
                return OutputPin.DisplayName.ToString();
            case ELuaBlueprintNodeType::LiteralBool:
                return Node.BoolValue ? "true" : "false";
            case ELuaBlueprintNodeType::LiteralInt:
                return std::to_string(Node.IntValue);
            case ELuaBlueprintNodeType::LiteralFloat:
                return FormatFloat(Node.FloatValue);
            case ELuaBlueprintNodeType::LiteralString:
                return LuaQuoted(Node.StringValue);
            case ELuaBlueprintNodeType::LiteralVector:
                return FormatVector(Node.VectorValue);
            case ELuaBlueprintNodeType::GetVariable:
            {
                const FString VarName = LuaName(Node.NameValue);
                if (VarName.empty())
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Error,
                        Node.NodeId,
                        "GetVariable has no variable name"
                    );
                    return "nil";
                }
                const FLuaBlueprintVariable* Variable = FindVariableByName(VarName);
                if (Variable && Variable->Type == ELuaBlueprintPinType::Object)
                {
                    return FString("__bp_get_var(") + LuaQuoted(VarName) + ")";
                }
                return FString("__vars[") + LuaQuoted(VarName) + "]";
            }
            case ELuaBlueprintNodeType::GetProperty:
            {
                const FString PropertyName = LuaName(Node.NameValue);
                if (PropertyName.empty())
                {
                    AddDiagnostic(
                        Result,
                        ELuaBlueprintDiagnosticSeverity::Error,
                        Node.NodeId,
                        "GetProperty has no property name"
                    );
                    return "nil";
                }
                return FString("Reflection.GetProperty(") + GetInputExpression(Node, "Target", "obj") + ", " +
                LuaQuoted(PropertyName) + ")";
            }
            case ELuaBlueprintNodeType::CallFunction:
            case ELuaBlueprintNodeType::CallFunctionSignature:
            {
                const FString Name = (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
                ? (!Node.StringValue.empty() ? Node.StringValue : LuaName(Node.NameValue)) : LuaName(Node.NameValue);
                if (Name.empty()) return "nil";
                auto It = ExecLocals.find(Node.NodeId);
                if (It != ExecLocals.end())
                {
                    return It->second;
                }
                return MakeCallExpression(Node, GetInputExpression(Node, "Target", "obj"), Name);
            }
            case ELuaBlueprintNodeType::AddFloat:
                return FString("(") + GetInputExpression(Node, "A", "0") + " + " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::SubtractFloat:
                return FString("(") + GetInputExpression(Node, "A", "0") + " - " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::MultiplyFloat:
                return FString("(") + GetInputExpression(Node, "A", "0") + " * " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::DivideFloat:
                return FString("__bp_safe_div(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(
                    Node,
                    "B",
                    "1"
                ) + ")";
            case ELuaBlueprintNodeType::AddInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " + " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::SubtractInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " - " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::MultiplyInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " * " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::DivideInt:
                // math.floor 로 truncate — Lua 정수 나눗셈은 5.3 부터 // 연산자, 호환성 위해 floor 사용.
                return FString("__bp_safe_idiv(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(
                    Node,
                    "B",
                    "1"
                ) + ")";
            case ELuaBlueprintNodeType::ModInt:
                return FString("__bp_safe_mod(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(
                    Node,
                    "B",
                    "1"
                ) + ")";
            case ELuaBlueprintNodeType::EqualFloat:
            case ELuaBlueprintNodeType::EqualInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " == " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::NotEqualFloat:
            case ELuaBlueprintNodeType::NotEqualInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " ~= " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::LessFloat:
            case ELuaBlueprintNodeType::LessInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " < " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::GreaterFloat:
            case ELuaBlueprintNodeType::GreaterInt:
                return FString("(") + GetInputExpression(Node, "A", "0") + " > " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::LessEqualFloat:
                return FString("(") + GetInputExpression(Node, "A", "0") + " <= " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::GreaterEqualFloat:
                return FString("(") + GetInputExpression(Node, "A", "0") + " >= " + GetInputExpression(Node, "B", "0") +
                ")";
            case ELuaBlueprintNodeType::And:
                return FString("(__bp_to_bool(") + GetInputExpression(Node, "A", "false") + ") and __bp_to_bool(" + GetInputExpression(
                    Node,
                    "B",
                    "false"
                ) + "))";
            case ELuaBlueprintNodeType::Or:
                return FString("(__bp_to_bool(") + GetInputExpression(Node, "A", "false") + ") or __bp_to_bool(" + GetInputExpression(
                    Node,
                    "B",
                    "false"
                ) + "))";
            case ELuaBlueprintNodeType::Not:
                return FString("(not __bp_to_bool(") + GetInputExpression(Node, "A", "false") + "))";
            case ELuaBlueprintNodeType::AppendString:
                // tostring 으로 감싸 숫자/bool 도 안전.
                return FString("(tostring(") + GetInputExpression(Node, "A", "\"\"") + ") .. tostring(" +
                GetInputExpression(Node, "B", "\"\"") + "))";
            case ELuaBlueprintNodeType::MakeVector:
                return FString("Vector(") + GetInputExpression(Node, "X", "0") + ", " + GetInputExpression(
                    Node,
                    "Y",
                    "0"
                ) + ", " + GetInputExpression(Node, "Z", "0") + ")";
            case ELuaBlueprintNodeType::BreakVector:
            {
                const FString V    = GetInputExpression(Node, "V", "Vector(0,0,0)");
                const FString Name = OutputPin.DisplayName.ToString();
                if (Name == "X" || Name == "Y" || Name == "Z")
                {
                    return FString("((") + V + ")." + Name + ")";
                }
                return "0";
            }
            case ELuaBlueprintNodeType::AddVector:
                return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") + (" + GetInputExpression(
                    Node,
                    "B",
                    "Vector(0,0,0)"
                ) + "))";
            case ELuaBlueprintNodeType::SubtractVector:
                return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") - (" + GetInputExpression(
                    Node,
                    "B",
                    "Vector(0,0,0)"
                ) + "))";
            case ELuaBlueprintNodeType::ScaleVector:
                return FString("((") + GetInputExpression(Node, "V", "Vector(0,0,0)") + ") * (" + GetInputExpression(
                    Node,
                    "Scale",
                    "1"
                ) + "))";
            case ELuaBlueprintNodeType::DotVector:
                return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + "):Dot(" + GetInputExpression(
                    Node,
                    "B",
                    "Vector(0,0,0)"
                ) + "))";
            case ELuaBlueprintNodeType::CrossVector:
                return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + "):Cross(" + GetInputExpression(
                    Node,
                    "B",
                    "Vector(0,0,0)"
                ) + "))";
            case ELuaBlueprintNodeType::VectorLength:
                return FString("((") + GetInputExpression(Node, "V", "Vector(0,0,0)") + "):Length())";
            case ELuaBlueprintNodeType::NormalizeVector:
                return FString("__bp_safe_norm(") + GetInputExpression(Node, "V", "Vector(0,0,0)") + ")";
            case ELuaBlueprintNodeType::Self:
                return "obj";
            case ELuaBlueprintNodeType::ForLoop:
            {
                if (OutputPin.DisplayName.ToString() == "Index")
                {
                    auto It = LoopIndexNodeIds.find(Node.NodeId);
                    return (It != LoopIndexNodeIds.end()) ? It->second : FString("0");
                }
                return "nil";
            }
            case ELuaBlueprintNodeType::CustomEvent:
            {
                // 함수 signature 의 파라미터 이름과 1:1. CustomEvent 의 Then exec 하류에서만 의미 있음.
                const FString PinName = OutputPin.DisplayName.ToString();
                if (PinName == "Arg0" || PinName == "Arg1" || PinName == "Arg2" || PinName == "Arg3")
                {
                    return PinName;
                }
                return "nil";
            }

            // ── Actor find / accessors ──
            case ELuaBlueprintNodeType::SpawnActor:
            case ELuaBlueprintNodeType::Cast:
            case ELuaBlueprintNodeType::BindEvent:
            {
                auto It = ExecLocals.find(Node.NodeId);
                return It != ExecLocals.end() ? It->second : FString("nil");
            }
            case ELuaBlueprintNodeType::HasEventBinding:
                return FString("Reflection.HasEventBinding(") + GetInputExpression(Node, "Target", "obj") + ", " + LuaQuoted(LuaName(Node.NameValue)) + ")";
            case ELuaBlueprintNodeType::FindActorByName:
                return FString("World.FindActorByName(") + GetInputExpression(
                    Node,
                    "Name",
                    LuaQuoted(Node.StringValue)
                ) + ")";
            case ELuaBlueprintNodeType::FindActorByClass:
                return FString("World.FindFirstActorByClass(") + LuaQuoted(LuaName(Node.NameValue)) + ")";
            case ELuaBlueprintNodeType::FindActorByTag:
                return FString("World.FindFirstActorByTag(") + GetInputExpression(
                    Node,
                    "Tag",
                    LuaQuoted(Node.StringValue)
                ) + ")";
            case ELuaBlueprintNodeType::FindActorsByTag:
                return FString("World.FindActorsByTag(") + GetInputExpression(
                    Node,
                    "Tag",
                    LuaQuoted(Node.StringValue)
                ) + ")";
            case ELuaBlueprintNodeType::FindActorsByClass:
                return FString("World.FindActorsByClass(") + LuaQuoted(LuaName(Node.NameValue)) + ")";
            case ELuaBlueprintNodeType::GetActorLocation:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Location or Vector(0,0,0))";
            case ELuaBlueprintNodeType::GetActorRotation:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Rotation or Vector(0,0,0))";
            case ELuaBlueprintNodeType::GetActorScale:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Scale or Vector(1,1,1))";
            case ELuaBlueprintNodeType::GetActorForward:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Forward or Vector(1,0,0))";
            case ELuaBlueprintNodeType::GetActorRight:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Right or Vector(0,1,0))";
            case ELuaBlueprintNodeType::ActorHasTag:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + "):HasTag(" + GetInputExpression(Node, "Tag", LuaQuoted("")) + ") or false)";
            case ELuaBlueprintNodeType::GetActorName:
                return FString("(") + GetInputExpression(Node, "Target", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Target",
                    "obj"
                ) + ").Name or \"\")";
            case ELuaBlueprintNodeType::GetOwnerActor:
                return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(
                    Node,
                    "Component",
                    "nil"
                ) + "):GetOwner() or nil)";

            // ── Object utility ──
            case ELuaBlueprintNodeType::IsValid:
            {
                const FString Target = GetInputExpression(Node, "Target", "nil");
                return FString("(") + Target + " ~= nil and (" + Target + "):IsValid())";
            }

            // ── Component getters ──
            case ELuaBlueprintNodeType::GetRootComponent:
                return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Actor",
                    "obj"
                ) + "):GetRootPrimitiveComponent() or nil)";
            case ELuaBlueprintNodeType::GetComponentByName:
                return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" +
                GetInputExpression(Node, "Actor", "obj") + "):GetComponentByName(" + GetInputExpression(
                    Node,
                    "Name",
                    LuaQuoted(Node.StringValue)
                ) + ") or nil)";
            case ELuaBlueprintNodeType::GetPrimitiveComponent:
                return FString("(") + GetInputExpression(Node, "Actor", "obj") + " and (" + GetInputExpression(
                    Node,
                    "Actor",
                    "obj"
                ) + "):GetPrimitiveComponent() or nil)";
            case ELuaBlueprintNodeType::GetLinearVelocity:
                return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(
                    Node,
                    "Component",
                    "nil"
                ) + "):GetLinearVelocity() or Vector(0,0,0))";
            case ELuaBlueprintNodeType::GetMass:
                return FString("(") + GetInputExpression(Node, "Component", "nil") + " and (" + GetInputExpression(
                    Node,
                    "Component",
                    "nil"
                ) + "):GetMass() or 0)";

            // ── Math util ──
            case ELuaBlueprintNodeType::Lerp:
            {
                const FString A = GetInputExpression(Node, "A", "0");
                const FString B = GetInputExpression(Node, "B", "0");
                const FString T = GetInputExpression(Node, "Alpha", "0");
                return FString("((1 - ") + T + ") * " + A + " + " + T + " * " + B + ")";
            }
            case ELuaBlueprintNodeType::Clamp:
                return FString("math.max(") + GetInputExpression(Node, "Min", "0") + ", math.min(" + GetInputExpression(
                    Node,
                    "Max",
                    "0"
                ) + ", " + GetInputExpression(Node, "Value", "0") + "))";
            case ELuaBlueprintNodeType::Min:
                return FString("math.min(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(
                    Node,
                    "B",
                    "0"
                ) + ")";
            case ELuaBlueprintNodeType::Max:
                return FString("math.max(") + GetInputExpression(Node, "A", "0") + ", " + GetInputExpression(
                    Node,
                    "B",
                    "0"
                ) + ")";
            case ELuaBlueprintNodeType::RandomFloat:
            {
                const FString Lo = GetInputExpression(Node, "Min", "0");
                const FString Hi = GetInputExpression(Node, "Max", "1");
                return FString("__bp_safe_random_float(") + Lo + ", " + Hi + ")";
            }
            case ELuaBlueprintNodeType::RandomInt:
                return FString("__bp_safe_random_int(") + GetInputExpression(Node, "Min", "0") + ", " +
                GetInputExpression(Node, "Max", "0") + ")";
            case ELuaBlueprintNodeType::Sin:
                return FString("math.sin(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::Cos:
                return FString("math.cos(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::Sqrt:
                return FString("__bp_safe_sqrt(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::AbsFloat:
                return FString("math.abs(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::Floor:
                return FString("math.floor(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::Ceil:
                return FString("math.ceil(") + GetInputExpression(Node, "Value", "0") + ")";
            case ELuaBlueprintNodeType::Distance:
                return FString("((") + GetInputExpression(Node, "A", "Vector(0,0,0)") + ") - (" + GetInputExpression(
                    Node,
                    "B",
                    "Vector(0,0,0)"
                ) + ")):Length()";

            case ELuaBlueprintNodeType::Reroute:
                return GetInputExpression(Node, "In", "nil");
            case ELuaBlueprintNodeType::ToBool:
                return FString("__bp_to_bool(") + GetInputExpression(Node, "Value", "nil") + ")";
            case ELuaBlueprintNodeType::ToInt:
                return FString("__bp_to_int(") + GetInputExpression(Node, "Value", "nil") + ")";
            case ELuaBlueprintNodeType::ToFloat:
                return FString("__bp_to_float(") + GetInputExpression(Node, "Value", "nil") + ")";
            case ELuaBlueprintNodeType::ToString:
                return FString("__bp_to_string(") + GetInputExpression(Node, "Value", "nil") + ")";
            case ELuaBlueprintNodeType::ToVector:
                return FString("__bp_to_vector(") + GetInputExpression(Node, "Value", "nil") + ")";

            // ── Time ──
            case ELuaBlueprintNodeType::GetGameTime:
                return "World.GetGameTime()";

            // ── ForEachActor ──
            case ELuaBlueprintNodeType::ForEachActorByClass:
            case ELuaBlueprintNodeType::ForEachActorByTag:
            case ELuaBlueprintNodeType::ForEachArray:
            {
                const FString PinName = OutputPin.DisplayName.ToString();
                if (PinName == "Actor" || PinName == "Item")
                {
                    auto It = ForEachActorNodeIds.find(Node.NodeId);
                    return It != ForEachActorNodeIds.end() ? It->second : FString("nil");
                }
                if (PinName == "Index")
                {
                    auto It = LoopIndexNodeIds.find(Node.NodeId);
                    return It != LoopIndexNodeIds.end() ? It->second : FString("0");
                }
                return "nil";
            }

            default:
                return "nil";
            }
        }

        FString MakeCallExpression(const FLuaBlueprintNode& Node, const FString& Target, const FString& Name)
        {
            TArray<std::pair<int32, FString>> Args;
            int32                             MaxArgIndex = -1;
            for (const FLuaBlueprintPin& Pin : Node.Pins)
            {
                if (Pin.Kind != ELuaBlueprintPinKind::Input || Pin.Type == ELuaBlueprintPinType::Exec)
                {
                    continue;
                }

                const FString PinName = Pin.DisplayName.ToString();
                if (PinName.rfind("Arg", 0) != 0)
                {
                    continue;
                }

                const FString IndexText = PinName.substr(3);
                if (IndexText.empty())
                {
                    continue;
                }

                const int32              Index = std::atoi(IndexText.c_str());
                const FLuaBlueprintLink* Link  = Asset.FindLinkToInput(Pin.PinId);
                if (!Link && Node.Type != ELuaBlueprintNodeType::CallFunctionSignature)
                {
                    continue;
                }

                if (Link)
                {
                    MaxArgIndex = std::max(MaxArgIndex, Index);
                    Args.push_back({ Index, GetInputExpression(Node, PinName.c_str(), "nil") });
                }
            }

            std::sort(
                Args.begin(),
                Args.end(),
                [](const auto& A, const auto& B)
                {
                    return A.first < B.first;
                }
            );

            FString Suffix;
            if (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature && MaxArgIndex >= 0)
            {
                for (int32 Index = 0; Index <= MaxArgIndex; ++Index)
                {
                    FString Value = "nil";
                    for (const auto& Arg : Args)
                    {
                        if (Arg.first == Index)
                        {
                            Value = Arg.second;
                            break;
                        }
                    }
                    Suffix += ", ";
                    Suffix += Value;
                }
            }
            else
            {
                for (const auto& Arg : Args)
                {
                    Suffix += ", ";
                    Suffix += Arg.second;
                }
            }

            if (Node.Type == ELuaBlueprintNodeType::CallFunctionSignature)
            {
                return FString("Reflection.CallSignature(") + Target + ", " + LuaQuoted(Name) + Suffix + ")";
            }
            return FString("Reflection.Call(") + Target + ", " + LuaQuoted(Name) + Suffix + ")";
        }

        void EmitIndent(std::ostringstream& Out, int Indent)
        {
            for (int I = 0; I < Indent; ++I)
            {
                Out << "    ";
            }
        }

        FString FormatFloat(float Value) const
        {
            char Buffer[64];
            std::snprintf(Buffer, sizeof(Buffer), "%.9g", Value);
            return Buffer;
        }

        FString FormatVector(const FVector& Value) const
        {
            return FString("Vector(") + FormatFloat(Value.X) + ", " + FormatFloat(Value.Y) + ", " + FormatFloat(Value.Z)
            + ")";
        }

    private:
        const ULuaBlueprintAsset&   Asset;
        FLuaBlueprintCompileResult& Result;
        // 활성 ForLoop 노드 → 그 노드의 Index pin 을 reference 하는 코드. nested loop 시 stack 처럼 사용.
        std::unordered_map<uint32, FString> LoopIndexNodeIds;
        // ForEachActor 노드 → 현재 iteration 의 actor 변수명. 위와 동일한 stack 의미.
        std::unordered_map<uint32, FString> ForEachActorNodeIds;
        // exec 측에서 발급한 데이터-반환 노드의 local 변수명 (SpawnActor / Cast 등).
        // 노드의 Then exec 가 emit 되는 동안 GetOutputExpression 이 이 local 을 참조한다.
        std::unordered_map<uint32, FString> ExecLocals;
        std::unordered_set<uint32>          DataStack;
    };
}

FLuaBlueprintCompileResult FLuaBlueprintCompiler::Compile(const ULuaBlueprintAsset& Asset)
{
    FLuaBlueprintCompileResult Result;
    FCompilerContext           Context(Asset, Result);
    Result.GeneratedLuaSource = Context.Compile();

    if (Asset.GetNodes().empty())
    {
        AddDiagnostic(Result, ELuaBlueprintDiagnosticSeverity::Warning, 0, "Blueprint has no nodes");
    }

    return Result;
}
